[package]
name = "left_right_struct"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1.6.0"
triomphe = {version = "0.1.9", features = ["arc-swap"]}